## Dockers setup for local development dependencies

version: "3"
services:
  ui:
    build:
      context: ./ui
    ports:
    - "7070:7070"
    environment:
      ORDER_HOST: host.docker.internal
    tty: true
    container_name: sarangui
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile.dev
    ports:
    - "8080:8080"
    environment:
      MONGO_HOST: host.docker.internal
      PAYMENT_HOST: host.docker.internal
    tty: true
    container_name: order-service
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    tty: true
    container_name: mongodb
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile.dev
    ports:
    - "9090:9090"
    tty: true
    container_name: payment-service
