apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: orderservice
    context: order-service
  - image: paymentservice
    context: payment-service
  - image: sarangui
    context: ui
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/*
profiles:
- name: gcb
  build:
    googleCloudBuild:
      projectId: sarangapp
- name: dev
  build:
    local: {}
    artifacts:
    - image: sarangui
      context: ui
    - image: orderservice
      context: order-service
      docker:
        dockerfile: Dockerfile.dev
    - image: orderservice
      context: order-service
      docker:
        dockerfile: Dockerfile.dev
