apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: sarangapp-ip
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: sarangui
          servicePort: 80