apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarangui
spec:
  selector:
    matchLabels:
      app: sarangui
  template:
    metadata:
      labels:
        app: sarangui
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: sarangui
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sarangui
spec:
  type: NodePort
  selector:
    app: sarangui
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP